In [1]:
import torch

# example 1

In [23]:
a = torch.randn(3, 4, requires_grad=True)
b = torch.randn(3, 4, requires_grad=True)
x = a + b * 2
y = x.sum()
y

tensor(0.3436, grad_fn=<SumBackward0>)

In [24]:
y.backward()
a.grad, b.grad  # pytorch default opening auto grad

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 tensor([[2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.]]))

# example 2

In [38]:
x = torch.rand(1)
b = torch.rand(1, requires_grad=True)
w = torch.rand(1, requires_grad=True)
y = w * x + b
y.backward()
b.grad, w.grad, x.grad # x has no autograd

(tensor([1.]), tensor([0.5626]), None)