## 1. Pytorch have auto grad module

In [1]:
import torch

x=torch.ones(2,2,requires_grad=True)
print(x)
y=x+2
print(y.grad_fn)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


## 2. add requires_grad automatically

In [2]:
a=torch.randn(2,2)
a=((a*3)/(a-1))
print(a)
print(a.requires_grad)

a.requires_grad_(True)
print(a.requires_grad)

b=(a*a).sum()
print(b.grad_fn)

tensor([[-1.4152,  1.1535],
        [ 0.2508,  1.1940]])
False
True


In [5]:
x=torch.randn(5,requires_grad=True)
y=torch.randn(5,requires_grad=True)
print(x)
print(y)
z=torch.sum(x+y)
print(z.grad_fn)
z.backward()
print(x.grad)
print(y.grad)

tensor([-0.1610,  1.8151, -0.5393, -0.2423, -0.0331], requires_grad=True)
tensor([-0.7952, -0.4188, -1.4992,  1.5435, -1.2567], requires_grad=True)
tensor([1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1.])


In [8]:
x=torch.randn(3,requires_grad=True)
y=x*2
print(y)
gradients=torch.tensor([0.1,1,0.0001],dtype=torch.float)
y.backward(gradients)
print(x.grad)

tensor([6.4491, 2.4430, 0.1925], grad_fn=<MulBackward0>)
tensor([2.0000e-01, 2.0000e+00, 2.0000e-04])
