1. scalar
2. vector
3. matrix
4. n-dimensional tensor

In [3]:
import torch

In [5]:
x=torch.tensor(42.)
x,x.dim(),x.item()

(tensor(42.), 0, 42.0)

In [7]:
v=torch.tensor([1,2,3])
v.dim()

1

In [9]:
mat=torch.tensor([[1,2],[3,4]])
mat,mat.dim(),mat*2,mat.matmul(mat)

(tensor([[1, 2],
         [3, 4]]),
 2,
 tensor([[2, 4],
         [6, 8]]),
 tensor([[ 7, 10],
         [15, 22]]))