In [3]:
import torch
print(torch.zeros(3,3))
print(torch.ones(3,3))
print(torch.randn(3,3))

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[-1.3548,  1.5846, -0.2523],
        [ 0.7568, -1.0935, -1.1821],
        [ 0.0584,  0.3790, -0.8310]])


In [4]:
a=torch.rand(4,4)
a=a.view(-1,8)
print(a)

tensor([[0.2431, 0.6030, 0.5307, 0.0647, 0.4773, 0.4326, 0.3624, 0.9708],
        [0.2200, 0.4596, 0.2166, 0.5048, 0.9798, 0.9431, 0.8529, 0.2625]])


In [5]:
b=a.numpy()
b

array([[0.24311012, 0.60295004, 0.53074473, 0.06469262, 0.4772613 ,
        0.43264073, 0.3623504 , 0.9707873 ],
       [0.22001374, 0.45959407, 0.21662408, 0.5048309 , 0.9798111 ,
        0.94311345, 0.852911  , 0.26247364]], dtype=float32)

In [6]:
import numpy as np
mat=np.ones(5)
b=torch.from_numpy(mat)
print(b)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


NameError: name 'b' is not defined